### PR TITLE
Development

### PR DESCRIPTION
**Pull request by DanielMitiku**

### CODE REVIEW

**Review by inhaq — CHANGES_REQUESTED** [review]
### Good first approach on using media queries 🏆
Awesome work guys but there is room for improvement.
[This](https://snag.gy/eNZRcJ.jpg) part is missing, kindly add it. 
Website isn't yet 100% responsive, kindly check it on small(320px) viewport and look for horizontal scrolling, kindly fix that as well. 
Images are not responsive on medium(<768px) viewport.
Text aren't handled on cards of `Latest News` correctly(check around 1100px).
Kindly make these tweaks and resubmit for review.

**Review by inhaq — CHANGES_REQUESTED** [review]
Good work guys, added required stuff but didn't fix images yet as they're not responsive. Also, [this](https://snag.gy/6yM9Ux.jpg) need to be fixed. Update path for [these](https://snag.gy/HYadjh.jpg) images. Once fixed, kindly resubmit.

**Comment by DanielMitiku** [comment]
Hey Inzi, can you please clarify when you say the images are not responsive. I think their size change according to the browser size.

**Comment by inhaq** [comment]
Its size and width shouldn't be stretched if the browser size is increased or decreased. [Here](https://www.w3schools.com/howto/howto_css_image_responsive.asp) is a good start.

**Comment by DanielMitiku** [comment]
Hey Inzi, but we tried to imitate the site. Have you looked how the site changes when the browser size changes? It's like ours.

**Comment by DanielMitiku** [comment]
the site is called thenextweb.com

**Comment by inhaq** [comment]
checked the site and it's not stretching images within `latest news`

**Comment by DanielMitiku** [comment]
Oh! I think you are talking about when the browser increases. We will fix that and resubmit

**Review by inhaq — CHANGES_REQUESTED** [review]
Hi guys, good work so far. A responsive website needs to be looking good on each device starting from mobile(320px) to big screens. You can increase and decrease browser size or go to inspect and look into it. [Here](https://snag.gy/ImgdhX.jpg), [here](https://snag.gy/UfqtJR.jpg), [here](https://snag.gy/2wPQYr.jpg), [here](https://snag.gy/qJSEl8.jpg) and [here](https://snag.gy/REhiTY.jpg) needs fixes.
If further explanation requires, kindly DM on slack.

**Review by inhaq — APPROVED** [review]
### It's a 👍🏻
Good work on site responsiveness. Go ahead and submit a project completion form. Good luck with the next project 🎉

**Pull request merged**
